version: '2'
volumes:
    odoo-postgresql-volume:
services:
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - odoo-postgresql-volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - "5432"
    odoo:
        image: odoo:10
        environment:
            - VIRTUAL_HOST=localhost
            - VIRTUAL_PORT=8069
            - PGHOST=db
            - PGUSER=odoo
            - PGPASSWORD=odoo
        volumes:
            - ./data/odoo/config:/etc/odoo
            - ./data/odoo/addons:/mnt/extra-addons
            - ./data/odoo/filestore:/var/lib/odoo/filestore
        tty: true
        depends_on:
            - db
        ports:
            - "8069:8069"
        expose:
            - "8069"
